# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeoStyler
                                 A QGIS plugin
 GeoStyler exporter
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-18
        copyright            : (C) 2024 by GeoStyler Team
        email                : sethg@geographika.net
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load GeoStyler class from file GeoStyler.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .geostyler import GeoStyler
    return GeoStyler(iface)
